.. topic:: Contribute!

   This documentation could use your help to grow and be refined. It is managed as a GitHub project at http://github.com/scala-ide/docs. Use the different available :doc:`tools </community>` to communicate with development team.

.. note::

       The documentation is redacted using `reStructuredText markup language <http://docutils.sourceforge.net/rst.html>`_ (reST). As with other `markup languages <http://en.wikipedia.org/wiki/Markup_language>`_, reST is the moral descendant of DocBook, and intended to be a lightweight way to structure text without having to deal with the presentation details involved in HTML. You can find references and tools for editing reST on its `wikipedia page <http://en.wikipedia.org/wiki/ReStructuredText>`_.
